### ISSUE TITLE
webvie那里会崩溃.

### ISSUE THREAD

**Issue by SimonHolmeslm** [lizhuoyuan/flutter_study#1]
flutter: 初始化路由
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001073201bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001068be735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010733ef44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000107324ed6 ___forwarding___ + 1446
	4   CoreFoundation                      0x0000000107326da8 _CF_forwarding_prep_0 + 120
	5   Runner                              0x00000001049f35d0 -[FlutterWebviewPlugin initWebview:] + 2832
	6   Runner                              0x00000001049f249e -[FlutterWebviewPlugin handleMethodCall:result:] + 254
	7   Flutter                             0x0000000104ab961a __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
	8   Flutter  <…>
Lost connection to device.

**Comment by lizhuoyuan** [comment]
发生了什么。。。
